### PR TITLE
doc(process types): Eliminate repition and generally polish

### PR DESCRIPTION
**Pull request by krancour**
There was a lot of repetition of information in the process type docs.  I think it told me _three_ times that the `Procfile` goes in the root of my application's source tree.  I've edited this page to be a bit more concise.

### CODE REVIEW

**Comment by slack** [comment]
Great changes. If you have a `--procfile` cli invocation handy it would be great to add that to the documentation, the syntax is not obvious.

**Comment by krancour** [comment]
@slack added an example of `deis pull` with `--procfile` option, as you suggested.

**Comment by slack** [comment]
Oh snap, I thought you had to pass in a YAML formatted string to `--procfile="---\n..."`, not a file ref.

**Comment by krancour** [comment]
@slack I didn't try it... now you have me second-guessing.  I will be sure to try it before I merge this.

**Comment by krancour** [comment]
@slack, you were right.  I'll have to fix it.

```
$ deis help pull
Creates a new build of an application. Imports an <image> and deploys it to Deis
as a new release. If a Procfile is present in the current directory, it will be used
as the default process types for this application.

Usage: deis builds:create <image> [options]

Arguments:
  <image>
    A fully-qualified docker image, either from Docker Hub (e.g. deis/example-go:latest)
    or from an in-house registry (e.g. myregistry.example.com:5000/example-go:latest).
    This image must include the tag.

Options:
  -a --app=<app>
    The uniquely identifiable name for the application.
  -p --procfile=<procfile>
    A YAML string used to supply a Procfile to the application.
```

**Comment by krancour** [comment]
@slack testing this out seems to have exposed a bug... seems process types other than the defaults (web for buildpacks and cmd otherwise) are not working at all.  It makes it hard to verify this functionality to include in the docs.  Going to open an issue in workflow and hold off on merging this for now.

**Comment by krancour** [comment]
Actually, it seems this issue is already captured by https://github.com/deis/workflow/issues/420.

**Comment by krancour** [comment]
I'm removing LGTMs to avoid this PR appearing at a glance to be mergeable.

**Comment by bacongobbler** [comment]
I think adding docs here are fine as long as that's the intentional behaviour. We'll fix up deis/workflow#420 to match the documentation.

**Comment by krancour** [comment]
Per @bacongobbler's suggestion, this can be re-reviewed and merged, I think.

**Pull request merged**
