### PR TITLE
Bring documentation in-line with Workflow terminology.

### PR DESCRIPTION
**Pull request by slack**
Use Workflow instead of Deis where it makes sense. Updated all links and page locations.

Of note, I also pulled out most of the left-side links because it was very easy to get yourself into deis.io hierarchy and back into v1 docs (especially via Overview). Helped a bit by #71 

Will be a bit of a rebase mess, but I'm happy to update this PR after #68 and #70 are merged.

### CODE REVIEW

**Comment by arschles** [comment]
@slack LGTM, but I'll hold off on labelling since you said you want to wait until #68 and #70 are merged. Let me know when you'd like a final review

**Comment by slack** [comment]
Just rebased now that the others are in. We still good with this?

**Comment by arschles** [comment]
LGTM3

**Comment by slack** [comment]
Good enough for me. :dancer:

**Pull request merged**
